### ISSUE TITLE
Differentiation of vector functions

### ISSUE THREAD

**Issue by bharswami** [auto-differentiation/xad#118]
Is it possible to have a feature to compute Jacobian? Differentiating a vector function with a vector of variables. 
Or is it already available?

**Comment by raneamri** [comment]
We're currently working on this feature and it should release in the near future. Note your issue is a duplicate of [Issue #37](https://github.com/auto-differentiation/xad/issues/37).

**Comment by bharswami** [comment]
Not going to be implemented?
