### ISSUE TITLE
Missing header in ChunkContainer.hpp?

### ISSUE THREAD

**Issue by JamesRogersMFE** [auto-differentiation/XAD#83]
**Describe the bug**
Reproduction of simple working examples leads to a compiler error:

`c++ unitialized_fill_n is not a member of std`

**To Reproduce**
Attempt to build a simple CLI app following code derived from the base example - unfortunately I cannot provide a complete example.

The main app creates a solver class with parameter structs defined using an AD type (either `xad::fwd<double>::active_type` or `xad::adj<double>::active_type`). All struct fields initialize derivatives as per examples in the docs and, in adjoint mode, create a tape with recording starting and stopping either side of primary code logic.

Occurs during both forward and adjoint modes.

**Required Fix**

The bug appears to be fixed by adding `#include <memory>` to the includes in `ChunkContainer.hpp` as per [C++ reference docs for std::uninitialized_fill_n](https://cplusplus.com/reference/memory/uninitialized_fill_n/).

**Environment (please complete the following information):**

-  Tag v1.2.0
-   Windows 10
-   MSVC++ v14.34.31933
-   Visual Studio 2022
-   CMake import via CPM.cmake

**Additional context**

I think there is a decent chance I have missed something here, so please let me know if this is a genuine issue. In the meantime, I can run off a fork with the fix described above in place.

**Comment by auto-differentiation-dev** [comment]
Thanks for flagging this. We will prepare a new release with the bugfix shortly.

**Comment by auto-differentiation-dev** [comment]
This has been fixed in release [v1.3.0](https://github.com/auto-differentiation/XAD/releases/tag/v1.3.0).
